/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 public/models/ufoLightrot4.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import EarthCanvas from './myCanvas'
import { motion } from 'framer-motion';
import './about.css'
import { Tilt } from 'react-tilt'
import { services } from '../constants';
import { fadeIn, textVariant } from '../utils/motion';




const ServiceCard = ({ title }) => {
    return (
      <Tilt className="">
        <motion.div  
          animate={{ rotate: 360, scale: 1 }}
          transition={{
            type: "spring",
            stiffness: 260,
            damping: 20
          }}
        className='tilty'>
        <div 
        options={{
          max: 45,
          scale: 1,
          speed: 450
        }}
        className='tilt-cards'
        >
          {/* <img src={icon} alt={title} className='w-16 h-16 object-contain' /> */}
        <h3 className=''>{title}</h3>
        </div>
        </motion.div>
  
      </Tilt>
  
    )
  }

const About = () => {

  return (
   <div id="about" className='main-container-about'>
    <div>
        <h1>Overview</h1>
        <p>
     My expertise lies in React, JavaScript, and CSS.
     Additionally, I specialize in implementing data-driven strategies using Google Analytics and Google Tag Manager.
     With a commitment to excellence and adaptability to diverse challenges, I am well-equipped to tackle any web development task. 
     Explore my projects to witness how I bring innovation and functionality to the digital world.
        </p>
    </div>
    <div>
    <div className='tilt-card-container'>
        {services.map((service, index) => (
          <ServiceCard key={service.title} index={index} {...service} />

        ))}
      </div>
    
    </div>

   </div>
  )
}

export default About

