/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 public/models/ufoLightrot4.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import MyCanvas from './myCanvas'
import { motion } from 'framer-motion';
import './hero.css'
import ScrollDown from './ScrollDown';

const Hero = () => {

    return (
        <div>
            <div className='main-container'>
                <div className='main-left'>
                    <motion.div
                        initial={{ opacity: 0, y: 100 }}
                        animate={{ opacity: 1, y: 0, }}
                        transition={{ duration: 1 }}
                    >
                        <h1 className='header-text'>Max Clayton</h1>
                        <p>I build things on the web</p>
                    </motion.div>
                </div>
                <div className='main-right'>
                    <MyCanvas />
                </div>
            </div>
            <ScrollDown />

        </div>

    )
}

export default Hero

