/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 public/models/ufoLightrot4.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const UFO = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('../models/ufoLightrot4.glb')
  const { actions } = useAnimations(animations, group)

  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Torus001" >
          <mesh name="Torus001_1" geometry={nodes.Torus001_1.geometry} material={materials['Material.011']} />
          <mesh name="Torus001_2" geometry={nodes.Torus001_2.geometry} material={materials.Material} />
          <mesh name="Torus001_3" geometry={nodes.Torus001_3.geometry} material={materials['Material.002']} />
          <mesh name="Torus001_4" geometry={nodes.Torus001_4.geometry} material={materials['Material.008']} />
          <mesh name="Torus001_5" geometry={nodes.Torus001_5.geometry} material={materials['Material.005']} />
          <mesh name="Torus001_6" geometry={nodes.Torus001_6.geometry} material={materials['Material.007']} />
          <mesh name="Torus001_7" geometry={nodes.Torus001_7.geometry} material={materials['Material.006']} />
          <mesh name="Torus001_8" geometry={nodes.Torus001_8.geometry} material={materials['Material.010']} />
        </group>
      </group>
    </group>
  )
}

export default UFO

useGLTF.preload('../models/ufoLightrot4.glb')
