/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 public/models/ufoLightrot4.glb 
*/

import React, { useRef } from 'react'
import { Chrono } from "react-chrono";
import { motion } from 'framer-motion';
import data from "./data";

import './work.css'


const Work = () => {

    return (
        <div className="work-container">
            <h1>Professional Experience</h1>
                   <Chrono   
                    theme={{
                    primary: "white",
                    secondary: "#5E00F0",
                    cardBgColor: "white",
                    cardForeColor: "violet",
                    titleColor: "white",
                    titleColorActive: "white",
                    
                    }}
                items={data}
                useReadMore={false}
                mode="HORIZONTAL" />
      </div>

    )
}

export default Work

